### ISSUE TITLE
Failure to apply metadata when MP3 length tag is present.

### ISSUE THREAD

**Issue by Java-SE-Binary** [asivery/webminidisc#32] opened 2023-11-20 22:18 UTC
When importing MP3 files that contain the 'length' tag present, the application falls on its face and is unable to import any of the other tags, only working off the filename, no matter the naming option selected. This does not cause an outright error, rather a failure to apply file metadata correctly.

**Comment by asivery** [comment] 2023-12-01 02:56
Hi there @Java-SE-Binary!
I can't seem to reproduce this bug. Would you be willing to share a file that causes the problem you're describing?
Thanks in advance :)

**Comment by Java-SE-Binary** [comment] 2023-12-01 04:40
Well this is embarrassing. The very same files are no longer giving me troubles. I'm not sure what could have changed since I made the post, but the metadata correctly imported when I tested the files again today. I uploaded an offending file just in case, linked [https://drive.google.com/file/d/1YsK5L2s8yU9tRtwnLn2JPIYKiCe9estA/view?usp=drive_link](url)

**Comment by asivery** [comment] 2023-12-25 04:07
@Java-SE-Binary I wasn't able to reproduce the issue when I applied the LENGTH tag manually onto some of my files, and the file you sent doesn't exhibit the issues you've mentioned. Since the file's name does match the ID3 tags, and it has no Album name defined in the tags, you might have selected a formatting option that included the missing album field. Selecting in Web Minidisc would result in it rendering the title as "Unknown Album - BEAT OF THE RISING SUN", which could have been misunderstood as the app not loading the tags at all.

If that's not the case, and you encounter this problem again, please reopen this issue. Right now I'm closing it as it wasn't reproducible.

**Closed by asivery** 2023-12-25 04:07 UTC
